### ISSUE TITLE
Conflict with lightboxes

### ISSUE THREAD

**Issue by amprsnd** [abeMedia/jquery-smoove#7]
Tested with: Fancybox, magnific-popup, tosrus popup lightbox

Google chrome: don't show images before reload page.
Lightboxes with jquery-smoove lose height value, and show image outside of offset. After reloading page all ok.
Firefox: sometimes buggy

(sorry my english)

**Comment by abeMedia** [comment]
Hi @amprsnd. Will look into this tomorrow. In the meantime you could try binding smoove to the lightbox event e.g. 
```
$(".foo").fancybox({ beforeShow: function() {
    $('.bar').smoove(options);
}});

**Comment by amprsnd** [comment]
Hello, @abeMedia . Thanks for the reply!
