### ISSUE TITLE
Opacity value do not works

### ISSUE THREAD

**Issue by thallysondias** [abeMedia/jquery-smoove#8]
I have this function:

```
$(".fadeup").smoove({
                offset  : '60px',
                moveY   : '5px',
                opacity : '20'
            });
```

Opacity 20% do not work,
works only if i leave the 0.

Its a bug or I do anything wrong?

**Comment by abeMedia** [comment]
Hi,

I just tried it and it works. Check this fiddle: http://jsfiddle.net/abemedia/p1tumn7x/

**Comment by thallysondias** [comment]
sry for lately aswer,
is works now :D 

Thanks.

**Comment by abeMedia** [comment]
Excellent!
