### ISSUE TITLE
crash with navbar

### ISSUE THREAD

**Issue by tefap93** [abeMedia/jquery-smoove#9]
When I initialize the code and animations starts to work my navbar just crash, it disappears from some point or literally breaks in two parts 
I'm also using AngularJs could this be the problem?

**Comment by abeMedia** [comment]
To have any idea what's going on I'll need to see you code (maybe a link to the project?).
I assume you are using classes in your navbar that you're also using for your animated objects...

**Comment by tefap93** [comment]
Nope I wasn't i assumed it was a crash between Angular JS and Jquery so
sadly I had to work with another scroll effects library; but i really like
yours I hope I can use it in some other project I was over my deadline so I
had no time for try more ways to fix it either way thank you very much

2016-08-02 22:39 GMT-04:30 Adam Bouqdib <notifications@github.com>:
